package com.eventfinder.app.client.createevent

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.eventfinder.app.domain.model.Event
import com.eventfinder.app.domain.model.EventCategory
import com.eventfinder.app.domain.model.EventLocation
import com.eventfinder.app.domain.model.EventVisibility
import com.eventfinder.app.domain.usecase.CreateEventUseCase
import com.eventfinder.app.domain.usecase.GetEventCategoriesUseCase
import com.eventfinder.app.domain.usecase.auth.GetCurrentUserUseCase
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch
import javax.inject.Inject

/**
 * ViewModel for creating events
 * Handles business logic and state management for event creation
 */
@HiltViewModel
class CreateEventViewModel @Inject constructor(
    private val createEventUseCase: CreateEventUseCase,
    private val getEventCategoriesUseCase: GetEventCategoriesUseCase,
    private val getCurrentUserUseCase: GetCurrentUserUseCase,
    private val draftPreferences: com.eventfinder.app.data.local.DraftPreferences
) : ViewModel() {

    private val _uiState = MutableStateFlow<CreateEventUiState>(CreateEventUiState.Idle)
    val uiState: StateFlow<CreateEventUiState> = _uiState.asStateFlow()

    private val _draftState = MutableStateFlow<DraftState>(DraftState.Idle)
    val draftState: StateFlow<DraftState> = _draftState.asStateFlow()
    
    private val _categories = MutableStateFlow<List<EventCategory>>(emptyList())
    val categories: StateFlow<List<EventCategory>> = _categories.asStateFlow()

    private val _isCategoriesLoading = MutableStateFlow(true)
    val isCategoriesLoading: StateFlow<Boolean> = _isCategoriesLoading.asStateFlow()
    
    init {
        loadCategories()
    }
    
    fun loadCategories() {
        viewModelScope.launch {
            _isCategoriesLoading.value = true
            // First get the current user to know their offered categories
            val userResult = getCurrentUserUseCase()
            val user = userResult.getOrNull()
            val offeredCategoryIds = user?.organizerProfile?.offeredEvents.orEmpty()
            
            getEventCategoriesUseCase().fold(
                onSuccess = { list ->
                    // Filter down to only those categories present in the user's offeredEvents profile
                    val filteredList = if (offeredCategoryIds.isNotEmpty()) {
                        list.filter { offeredCategoryIds.contains(it.id) }
                    } else {
                        // Fallback: If no categories found in profile, show all or handle appropriately
                        list
                    }
                    _categories.value = filteredList
                    _isCategoriesLoading.value = false
                },
                onFailure = {
                    _categories.value = emptyList()
                    _isCategoriesLoading.value = false
                }
            )
        }
    }

    /**
     * Create a new event and publish it
     */
    fun createEvent(
        title: String,
        description: String,
        category: EventCategory,
        startTimeMillis: Long,
        endTimeMillis: Long?,
        locationName: String,
        latitude: Double,
        longitude: Double,
        address: String?,
        maxParticipants: Int?,
        isFree: Boolean,
        price: Double?,
        currency: String?,
        organizerId: String,
        organizerName: String,
        tags: List<String> = emptyList(),
        visibility: EventVisibility = EventVisibility.PUBLIC,
        requiresTicket: Boolean = false
    ) {
        viewModelScope.launch {
            _uiState.value = CreateEventUiState.Loading

            try {
                val event = Event(
                    id = "", // Will be generated by data source
                    eventId = "",
                    title = title.trim(),
                    description = description.trim(),
                    category = category,
                    organizerId = organizerId,
                    organizerName = organizerName,
                    organizerPhotoUrl = null,
                    organizerSocialLinks = null,
                    startTime = startTimeMillis,
                    endTime = endTimeMillis,
                    location = EventLocation(
                        latitude = latitude,
                        longitude = longitude
                    ),
                    address = address?.trim(),
                    maxParticipants = maxParticipants,
                    currentParticipantCount = 0,
                    isFree = isFree,
                    price = if (!isFree) price else null,
                    currency = if (!isFree) currency else null,
                    imageUrls = generateDummyImageUrls(category),
                    mainImageUrl = generateDummyImageUrls(category).firstOrNull(),
                    tags = tags,
                    visibility = visibility,
                    requiresTicket = requiresTicket,
                    createdAt = System.currentTimeMillis(),
                    updatedAt = null,
                    distanceKm = null,
                    isUserParticipating = false,
                    isUserOrganizer = true,
                    state = com.eventfinder.app.domain.model.EventState.SCHEDULED,
                    publishedAt = System.currentTimeMillis()
                )

                android.util.Log.d("CreateEventViewModel", "Creating event with userId: $organizerId")

                val result = createEventUseCase(event)

                result.fold(
                    onSuccess = { createdEvent ->
                        android.util.Log.d("CreateEventViewModel", "Event created successfully: ${createdEvent.id}")
                        _uiState.value = CreateEventUiState.Success(createdEvent)
                    },
                    onFailure = { error ->
                        android.util.Log.e("CreateEventViewModel", "Failed to create event", error)
                        _uiState.value = CreateEventUiState.Error(
                            error.message ?: "Failed to create event"
                        )
                    }
                )
            } catch (e: Exception) {
                _uiState.value = CreateEventUiState.Error(
                    e.message ?: "An unexpected error occurred"
                )
            }
        }
    }

    /**
     * Save event as draft to local storage
     */
    fun saveDraft(
        title: String,
        description: String?,
        selectedCategories: List<EventCategory>,
        startTimeMillis: Long?,
        endTimeMillis: Long?,
        locationName: String?,
        latitude: Double?,
        longitude: Double?,
        address: String?,
        maxParticipants: Int?,
        isFree: Boolean,
        price: Double?,
        currency: String?,
        organizerId: String,
        tags: List<String>,
        visibility: EventVisibility,
        requiresTicket: Boolean
    ) {
        viewModelScope.launch {
            _draftState.value = DraftState.Saving

            try {
                val draft = com.eventfinder.app.domain.model.EventDraft(
                    title = title.trim(),
                    description = description?.trim(),
                    selectedCategories = selectedCategories,
                    startTimeMillis = startTimeMillis,
                    endTimeMillis = endTimeMillis,
                    locationName = locationName,
                    latitude = latitude,
                    longitude = longitude,
                    address = address,
                    maxParticipants = maxParticipants,
                    isFree = isFree,
                    price = price,
                    currency = currency,
                    tags = tags,
                    visibility = visibility,
                    requiresTicket = requiresTicket,
                    organizerId = organizerId
                )

                draftPreferences.saveDraft(draft)

                _draftState.value = DraftState.Saved
            } catch (e: Exception) {
                _draftState.value = DraftState.Error(
                    e.message ?: "Failed to save draft"
                )
            }
        }
    }

    /**
     * Load a draft by ID
     */
    fun loadDraft(draftId: String): com.eventfinder.app.domain.model.EventDraft? {
        return draftPreferences.getDraft(draftId)
    }

    /**
     * Get all saved drafts
     */
    fun getAllDrafts(): List<com.eventfinder.app.domain.model.EventDraft> {
        return draftPreferences.getAllDrafts()
    }

    /**
     * Delete a specific draft
     */
    fun deleteDraft(draftId: String) {
        draftPreferences.deleteDraft(draftId)
    }

    /**
     * Reset UI state to idle
     */
    fun resetState() {
        _uiState.value = CreateEventUiState.Idle
        _draftState.value = DraftState.Idle
    }

    /**
     * Generate dummy image URLs based on event category
     */
    private fun generateDummyImageUrls(category: EventCategory): List<String> {
        return when (category.id) {
            "cat_sports", "cat_fitness" -> listOf(
                "https://images.unsplash.com/photo-1461896836934-ffe607ba8211",
                "https://images.unsplash.com/photo-1517649763962-0c623066013b"
            )
            "cat_music", "cat_qawwali" -> listOf(
                "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3",
                "https://images.unsplash.com/photo-1459749411175-04bf5292ceea"
            )
            "cat_food" -> listOf(
                "https://images.unsplash.com/photo-1555939594-58d7cb561ad1",
                "https://images.unsplash.com/photo-1504674900247-0877df9cc836"
            )
            "cat_business", "cat_networking", "cat_real_estate" -> listOf(
                "https://images.unsplash.com/photo-1540575467063-178a50c2df87",
                "https://images.unsplash.com/photo-1559136555-9303baea8ebd"
            )
            "cat_workshops", "cat_tech" -> listOf(
                "https://images.unsplash.com/photo-1552664730-d307ca884978",
                "https://images.unsplash.com/photo-1531482615713-2afd69097998"
            )
            "cat_education", "cat_books" -> listOf(
                "https://images.unsplash.com/photo-1523240795612-9a054b0db644",
                "https://images.unsplash.com/photo-1427504494785-3a9ca7044f45"
            )
            "cat_arts_theatre", "cat_culture", "cat_mushaira", "cat_comedy" -> listOf(
                "https://images.unsplash.com/photo-1492684223066-81342ee5ff30",
                "https://images.unsplash.com/photo-1514525253161-7a46d19cd819"
            )
            "cat_charity", "cat_religion" -> listOf(
                "https://images.unsplash.com/photo-1511795409834-ef04bbd61622",
                "https://images.unsplash.com/photo-1528605248644-14dd04022da1"
            )
            else -> listOf(
                "https://images.unsplash.com/photo-1492684223066-81342ee5ff30"
            )
        }
    }
}